[package]
name = "prpr-avc"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
sasa = { workspace = true, default-features = false }

[target.'cfg(target_os = "android")'.dependencies]
sasa = { workspace = true, default-features = false, features = ["oboe"] }

[target.'cfg(target_env = "ohos")'.dependencies]
sasa = { workspace = true, default-features = false, features = ["ohos"] }

[target.'cfg(not(any(target_os = "android", target_os = "windows", target_env = "ohos")))'.dependencies]
sasa = { workspace = true, default-features = false, features = ["cpal"] }

[build-dependencies]
flate2 = "1"
tar = "0.4"
ureq = "2"
